version: '3.1'

services:
  db:
    image: postgres:12
    restart: always
    container_name: enquizitive-db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - enquizitive

networks:
  enquizitive: