version: '3.1'

services:
  db:
    image: postgres:12
    restart: always
    container_name: enquizitive-db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - enquizitive

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./dynamodb-local:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - enquizitive

networks:
  enquizitive: